### ISSUE TITLE
Add Device Inventory Playbook

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/ansible_collection_centurion#13]
migrate internal device inventory playbook to this collection.

MR !1 will need to be completed first

## Links / References

- !1
- Blocked by: #15 
- Blocked by: #16 

migrated from https://gitlab.com/nofusscomputing/projects/ansible/collections/centurion_erp_collection/-/issues/1

**Comment by jon-nfc** [comment]
@jasonpagetas, assign yourself to this issue when you accept the invitation

**Comment by jasonpagetas** [comment]
As with #14 which branch of this repo do I fork?

**Comment by jon-nfc** [comment]
> As with #14 which branch of this repo do I fork?

The repository is forked, work is generally done on a separate feature branch within your fork and merged back to the development branch of this repo.

Work for both #13 and #14 can be done within the same PR if you prefer.

**Comment by jon-nfc** [comment]
I'll merge #16 so that the checks are part of your PR and you can commence work without issues popping up later. #15 will remain blocking for your PR's merge, until I complete it. 

You will need to rebase your fork to the updated (post merge) of #16.
