### ISSUE TITLE
Add Centurion teams configuration playbook

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/ansible_collection_centurion#14]
The centurion playbook from [production](https://gitlab.com/nofusscomputing/infrastructure/configuration-management/playbooks-production) will need to be migrated to this collection.

@jasonpagetas this would be a good issue for yourself to resolve.

## Links

- Blocked by: #15
- Blocked by: #16

**Comment by jasonpagetas** [comment]
Which branch do I fork?

Additionally do I need to migrate the config as well?

**Comment by jon-nfc** [comment]
> Which branch do I fork?

The repository is forked, work is generally done on a separate feature branch within your fork and merged back to the development branch of this repo.

Work for both #13 and #14 can be done within the same PR if you prefer.

> Additionally do I need to migrate the config as well?

**NO** that's internal **ONLY**

**Comment by jon-nfc** [comment]
I'll merge #16 so that the checks are part of your PR and you can commence work without issues popping up later. #15 will remain blocking for your PR's merge, until I complete it. 

You will need to rebase your fork to the updated (post merge) of #16.

**Comment by jasonpagetas** [comment]
In docs be sure to include a tip that the full list of permissions can be fetched via an api get request


https://github.com/nofusscomputing/centurion_erp/issues/164#issuecomment-2295188685
